# Generated by Django 3.2.18 on 2023-02-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('autor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Discos',
                'verbose_name_plural': 'Discos',
                'db_table': 'Discos',
            },
        ),
    ]
